/**
    Copyright (C) 2014 dhcrawl - Probe DHCPMessage servers to see what offers are sent

    Written by Tobias Eliasson <arnestig@gmail.com>.

    This file is part of dhcrawl https://github.com/arnestig/dhcrawl

    dhcrawl is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    dhcrawl is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with dhcrawl.  If not, see <http://www.gnu.org/licenses/>.
**/

#ifndef __DHCPOPTIONS_H__
#define __DHCPOPTIONS_H__

namespace DHCPOptions {
	enum MessageType {
		DHCPDISCOVER = 1,
		DHCPOFFER = 2,
		DHCPREQUEST = 3,
		DHCPDECLINE = 4,
		DHCPACK = 5,
		DHCPNAK = 6,
		DHCPRELEASE = 7,
		DHCPINFORM = 8
	};
	
	static const char *messageTypeName[] = { 
		"", 
		"DHCPDISCOVER", 
		"DHCPOFFER", 
		"DHCPREQUEST", 
		"DHCPDECLINE", 
		"DHCPACK", 
		"DHCPNAK", 
		"DHCPRELEASE", 
		"DHCPINFORM" 
	};

	static const char *optionName[] = { 
		"",
		"Subnet Mask",
		"Time Offset",
		"Router",
		"Time Server",
		"Name Server",
		"Domain Server",
		"Log Server",
		"Quotes Server",
		"LPR Server",
		"Impress Server",
		"RLP Server",
		"Hostname",
		"Boot File Size",
		"Merit Dump File",
		"Domain Name",
		"Swap Server",
		"Root Path",
		"Extension File",
		"Forward On/Off",
		"SrcRte On/Off",
		"Policy Filter",
		"Max DG Assembly",
		"Default IP TTL",
		"MTU Timeout",
		"MTU Plateau",
		"MTU Interface",
		"MTU Subnet",
		"Broadcast Address",
		"Mask Discovery",
		"Mask Supplier",
		"Router Discovery",
		"Router Request",
		"Static Route",
		"Trailers",
		"ARP Timeout",
		"Ethernet",
		"Default TCP TTL",
		"Keepalive Time",
		"Keepalive Data",
		"NIS Domain",
		"NIS Servers",
		"NTP Servers",
		"Vendor Specific",
		"NETBIOS Name Srv",
		"NETBIOS Dist Srv",
		"NETBIOS Node Type",
		"NETBIOS Scope",
		"X Window Font",
		"X Window Manager",
		"Address Request",
		"Address Time",
		"Overload",
		"DHCP Msg Type",
		"DHCP Server Id",
		"Parameter List",
		"DHCP Message",
		"DHCP Max Msg Size",
		"Renewal Time",
		"Rebinding Time",
		"Class Id",
		"Client Id",
		"NetWare/IP Domain",
		"NetWare/IP Option",
		"NIS-Domain-Name",
		"NIS-Server-Addr",
		"Server-Name",
		"Bootfile-Name",
		"Home-Agent-Addrs",
		"SMTP-Server",
		"POP3-Server",
		"NNTP-Server",
		"WWW-Server",
		"Finger-Server",
		"IRC-Server",
		"StreetTalk-Server",
		"STDA-Server",
		"User-Class",
		"Directory Agent",
		"Service Scope",
		"Rapid Commit",
		"Client FQDN",
		"Relay Agent Information",
		"iSNS",
		"",
		"NDS Servers",
		"NDS Tree Name",
		"NDS Context",
		"BCMCS Controller Domain Name list",
		"BCMCS Controller IPv4 address option",
		"Authentication",
		"client-last-transaction-time option",
		"associated-ip option",
		"Client System",
		"Client NDI",
		"LDAP",
		"",
		"UUID/GUID",
		"User-Auth",
		"GEOCONF_CIVIC",
		"PCode",
		"TCode",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"Netinfo Address",
		"Netinfo Tag",
		"URL",
		"",
		"Auto-Config",
		"Name Service Search",
		"Subnet Selection Option",
		"Domain Search",
		"SIP Servers DHCP Option",
		"Classless Static Route Option",
		"CCC",
		"GeoConf Option",
		"V-I Vendor Class",
		"V-I Vendor-Specific Information",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"OPTION_PANA_AGENT",
		"OPTION_V4_LOST",
		"OPTION_CAPWAP_AC_V4",
		"OPTION-IPv4_Address-MoS",
		"OPTION-IPv4_FQDN-MoS",
		"SIP UA Configuration Service Domains",
		"OPTION-IPv4_Address-ANDSF",
		"",
		"GeoLoc",
		"FORCERENEW_NONCE_CAPABLE",
		"RDNSS Selection",
		"",
		"",
		"",
		"TFTP server address",
		"status-code",
		"base-time",
		"start-time-of-state",
		"query-start-time",
		"query-end-time",
		"dhcp-state",
		"data-source",
		"OPTION_V4_PCP_SERVER",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"Etherboot",
		"IP Telephone",
		"Etherboot",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"PXELINUX Magic",
		"Configuration File",
		"Path Prefix",
		"Reboot Time",
		"OPTION_6RD",
		"OPTION_V4_ACCESS_DOMAIN",
		"",
		"",
		"",
		"",
		"",
		"",
		"Subnet Allocation Option",
		"VSS",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		""
	};
}

#endif
